name: TileGame
options:
  bundleIdPrefix: dev.pastre
packages:
  TileGameLib:
    path: TileGameLib/
targets:
  TileGame - iOS:
    type: application
    platform: iOS
    deploymentTarget: "14.0"
    sources: [iOS]
    info:
      path: iOS/Info.plist
      properties:
        CFBundleDisplayName: Hex Escape
        CFBundleExecutable: $(EXECUTABLE_NAME)
        CFBundleIdentifier: $(PRODUCT_BUNDLE_IDENTIFIER)
        CFBundleVersion: "1.0"
        UILaunchScreen:
          UILaunchScreen:
          
    dependencies:
      - package: TileGameLib
        product: TGCore
      - package: TileGameLib
        product: TGKit